In [10]:
import numpy as np

def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)

    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x+h)
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # f(x-h)
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2 * h)
        x[idx] = tmp_val

    return grad

In [2]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [11]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [12]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [13]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])

In [15]:
# lr = learning rate(学習率)
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x

In [16]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])